sonar.projectKey=webapp-component-core-main
sonar.projectName=webapp-component-core (main)

sonar.sources=src

sonar.issue.ignore.multicriteria=noTodoTags
sonar.issue.ignore.multicriteria.noTodoTags.ruleKey=javascript:S1135
sonar.issue.ignore.multicriteria.noTodoTags.resourceKey=**/*
